spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:D:/Programowanie/Java/[Spring][IntelliJ][Kurs]Udemy/MarcinRogoz-ToDoApp/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
task.template.allowMultipleTasks: false


